version: "3.9"

services:

  api:
    build: .
    container_name: crm_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/crm
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  celery_worker:
    build: .
    container_name: crm_celery_worker
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/crm
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: >
      celery -A app.workers.celery_app.celery_app worker --loglevel=info

  celery_beat:
    build: .
    container_name: crm_celery_beat
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/crm
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    command: >
      celery -A app.workers.celery_app.celery_app beat --loglevel=info 

  db:
    image: postgres:15-alpine
    container_name: crm_db
    restart: always
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: crm_redis
    ports:
      - "6380:6379"

volumes:
  postgres_data: